language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# commands to install dependencies
install:
  - python setup.py -q install
  - git clone https://github.com/ewels/MultiQC_TestData.git test_data
  - cd test_data
# commands to run tests
script:
  - multiqc data
  - multiqc data -f -i "Forced Report"
  - multiqc data -n custom_fn --no-data-dir -e fastqc
  - multiqc data -f -z -m fastqc
  - multiqc data -o tests/multiqc_report_dev -t default_dev -k json
  - multiqc data -o tests/multiqc_report_geo -t geo -k yaml -v
  