name: Docs - Netlify preview

on:
  pull_request:
    paths: ["docs/**"]
    # TODO: Remove / rename when new site is live
    branches: [docs-restructure]

jobs:
  deploy:
    name: "Deploy preview"
    runs-on: ubuntu-latest
    if: github.repository == 'ewels/MultiQC'
    defaults:
      run:
        working-directory: ./MultiQC_website
    permissions:
      statuses: write
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout MultiQC repo
        uses: actions/checkout@v3
        with:
          path: ./MultiQC

      - name: Checkout MultiQC website repo
        uses: actions/checkout@v3
        with:
          repository: ewels/MultiQC_website
          path: ./MultiQC_website
          # TODO: Swtich to master branch once merged
          ref: astro

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install npm deps
        run: npm install

      - name: Build website
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./MultiQC_website/dist"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "MultiQC PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          alias: mqc-pr-${{ github.event.pull_request.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
