name: Docs - Netlify deploy

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs_deploy.yml"

jobs:
  deploy:
    name: "Request deployment"
    runs-on: ubuntu-latest
    if: github.repository == 'ewels/MultiQC'
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
